
---
version: '3'
services:

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    depends_on:
      - nzbget
      - deluge
      - jackett
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${DOWNLOADS_PATH}/Complete/TV:/downloads
      - ${TV_PATH}:/tv
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  radarr:
    image: linuxserver/radarr:preview
    container_name: radarr
    depends_on:
      - nzbget
      - deluge
      - jackett
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${DOWNLOADS_PATH}/Complete/Movies:/downloads
      - ${MOVIES_PATH}:/movies
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    depends_on:
      - nzbget
      - deluge
      - jackett
    volumes:
      - ${APPDATA_PATH}/lidarr:/config
      - ${DOWNLOADS_PATH}/Complete/Music:/downloads
      - ${MUSIC_PATH}:/music
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: service:vpn
    depends_on:
      - vpn
    volumes:
      - ${APPDATA_PATH}/jackett/config:/config
      - ${APPDATA_PATH}/jackett/data:/downloads
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    depends_on:
      - vpn
    volumes:
      - ${APPDATA_PATH}/deluge:/config
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - ${APPDATA_PATH}/nzbget:/config
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
  
  # The VPN image serves as a router to mask the traffic from
  # Deluge and Jackett.  Sonarr, Radarr, and Lidarr do not require VPN
  # for anonymity.  Neither does NzbGet.
  vpn:
    image: azinchen/nordvpn
    container_name: vpn
    depends_on: []
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - 9117:9117 # Jackett port
      - 8112:8112 # Torrent UI port
    environment:
      - TZ=${TZ}
      - USER=${VPN_USER}
      - PASS=${VPN_PASS}
      - COUNTRY=United States
      - CATEGORY=P2P
      - PROTOCOL=openvpn_udp
  
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - vpn
    volumes:
      - ${APPDATA_PATH}/nginx/html:/usr/share/nginx/html:ro       # Place static HTML here
      - ${APPDATA_PATH}/certbot/html:/var/www/certbot:ro          # Place certbot HTML here
      - ${APPDATA_PATH}/certbot/conf:/etc/letsencrypt:ro          # Place SSL certs here
      - ${APPDATA_PATH}/nginx/conf:/etc/nginx/conf:ro             # Place additional config files (htpassword, etc.) here
      - ${APPDATA_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Place nginx.conf file here
      - ${APPDATA_PATH}/nginx/logs:/etc/nginx/logs                # Direct log files here
    links:
      - vpn:jackett
      - vpn:deluge
    ports:
      - 80:80
      - 443:443